export const FUNCTION_SAFE_IMAGE_UPLOAD_MAX_BYTES = 4 * 1024 * 1024;
export const FUNCTION_SAFE_IMAGE_UPLOAD_MAX_LABEL = "4MB";

export const BRANDING_IMAGE_UPLOAD_MAX_BYTES = 2 * 1024 * 1024;
export const BRANDING_IMAGE_UPLOAD_MAX_LABEL = "2MB";
